---
- name: msmtp role
  tags:
  - msmtp
  block:

  # assert
  - name: Assertions for role msmtp
    ansible.builtin.assert:
      that:
      - msmtp_msmtprc_template != None

  # mail.rc
  - name: Write /etc/mail.rc 
    become: true
    ansible.builtin.copy:
      content: "set sendmail=/usr/bin/msmtp"
      dest: /etc/mail.rc
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

  # apt
  - ansible.builtin.import_tasks: msmtp-apt.yml

  # config
  - ansible.builtin.import_tasks: msmtp-config.yml

  # service
  - ansible.builtin.import_tasks: msmtp-service.yml
