---
- name: msmtp role
  tags:
  - msmtp
  block:

  # assert
  - name: Assertions for role msmtp
    ansible.builtin.assert:
      that:
      - msmtp_msmtprc_template != None

  # apt
  - ansible.builtin.import_tasks: msmtp-apt.yml

  # config
  - ansible.builtin.import_tasks: msmtp-config.yml

  # service
  - ansible.builtin.import_tasks: msmtp-service.yml
