---
- tags: [role-msmtp-msmtpd]
  block:

  # msmtpd.service
  - name: Set enabled {{ msmtp_msmtpd_enabled }} on msmtpd.service
    become: true
    ansible.builtin.systemd_service:
      name: msmtpd.service
      enabled: "{{ msmtp_msmtpd_enabled }}"
      state: "{{ 'stopped' if msmtp_msmtpd_enabled == false else 'started' }}"