---
- tags: [msmtp-config]
  block:

  # template msmtprc
  - name: Template msmtprc
    become: true
    notify: Restart msmtpd.service
    ansible.builtin.template:
      src: "{{ msmtp_msmtprc_template }}"
      dest: /etc/msmtprc
      owner: root
      group: root
      mode: "{{ msmtp_msmtprc_mode }}"

  # cp aliases
  - when: msmtp_aliases != None
    name: Copy aliases
    become: true
    notify: Restart msmtpd.service
    ansible.builtin.copy:
      src: "{{ msmtp_aliases }}"
      dest: /etc/aliases
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

  # cp mail.rc
  - when: msmtp_mailrc != None
    name: Copy {{ msmtp_mailrc }}
    become: true
    notify: Restart msmtpd.service
    ansible.builtin.copy:
      src: "{{ msmtp_mailrc }}"
      dest: /etc/mail.rc
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"